"""Initial migration.

Revision ID: b12b3bab2d85
Revises: 
Create Date: 2022-02-02 16:27:11.081777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b12b3bab2d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sound_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sound_id')
    )
    op.add_column('sounds', sa.Column('audiofile', sa.LargeBinary(), nullable=False))
    op.drop_constraint('sounds_uploader_fkey', 'sounds', type_='foreignkey')
    op.drop_column('sounds', 'uploader')
    op.drop_column('sounds', 'sound_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sounds', sa.Column('sound_file', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('sounds', sa.Column('uploader', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sounds_uploader_fkey', 'sounds', 'users', ['uploader'], ['id'])
    op.drop_column('sounds', 'audiofile')
    op.drop_table('uploads')
    # ### end Alembic commands ###
